### ISSUE TITLE
PuLp 2.0 failed to run pulptest

### ISSUE THREAD

**Issue by rwv** [coin-or/pulp#253]
PuLp 2.0 (installed from PyPI) failed to run `pulptest`.

Error output:
``` 
Traceback (most recent call last):
  File "/Users/user1/.pyenv/versions/ver1/bin/pulptest", line 5, in <module>
    from tests.run_tests import pulpTestAll
ModuleNotFoundError: No module named 'tests'
```

OS: `64bit Mac OS X 10.15.1 19B88`
Python version: `3.6.6`

p.s.
PuLp 1.6.10 could pass `pulptest`

**Comment by pchtsp** [comment]
Hello and thanks for pointing that out. In fact, tests are now supposed to be run by downloading the git repository and then running:
```
python tests/run_tests.py
```

So I think they are not included inside the package anymore. We still need to figure out a way to warn the user or fix this...

**Comment by stumitchell** [comment]
I'll see if I can change the setup.py to keep this functionality, it is
important that end users can run tests

Stu

Stuart Mitchell
PhD Engineering Science
Extraordinary Freelance Programmer and Optimisation Guru
www.stuartmitchell.com

**Comment by sorinmuchi** [comment]
Understatement of the year

**Comment by pchtsp** [comment]
@stumitchell 
Is it important to run all PuLP tests from the package? Or to report which solvers are available to PuLP in the concerned system from the package? I've always thought that if one really wants to run the development tests, one should download the repo. I'm not sure how other projects handle this.

**Comment by stumitchell** [comment]
Sure the user needs to only know what is available, and running the tests answers that question.

Plus our documentation refers to running tests to confirm the setup.

And this worked so it is a regression rather than a feature.

Our tests are fairly lightweight so I don't believe that we get any benefit excluding normal users from running them. Also it does save some time debugging if users can quickly run tests and report their output.

So I think they should be added back into the main package

**Comment by jerrytim** [comment]
hey @stumitchell , I ran into this issue, is there any update on this?

**Comment by pchtsp** [comment]
Hello! We have a PR with the change already: https://github.com/coin-or/pulp/pull/264
We will be possibly merging it soon into the master branch.

If you want to test it to confirm it works for you, you could do: 

```
pip install git+https://github.com/coin-or/pulp@add_tests_to_package
```

F.

**Comment by laffmaluf** [comment]
Hello pchtsp, my Python version is 3.8.2, and the command
C:\\ ... Python38-32\Scripts>py -3.8 -m pip install git+https://github.com/coin-or/pulp@add_tests_to_package
returns this error message: "ERROR: could not find command git. Do you have installed in your pathw

Then a tried first to install git doing 
C:\\ ... Python38-32\Scripts>py -3.8 -m pip install git
the Windows command prompt shows this other error message: "ERROR: could not find a version that satysfies the requirement git.

Any idea how to solve this problems?

**Comment by pchtsp** [comment]
Good day,

1, git is not a python package. You need to download it, install it and configure it to be added to your PATH: https://git-scm.com/downloads
2. You can now install from the master branch as the PR was merged already:

```
pip install git+https://github.com/coin-or/pulp
```

I'm going to close this issue as the problem has been solved.

**Comment by jerrytim** [comment]
@pchtsp will there be an update to PyPI? if do `pip install pulp` we still have this issue, otherwise we can only uninstall and reinstall?

**Comment by khalida** [comment]
If pulp is removed and then re-installed using pip - should the `pulp.pulpTestAll()` method be available? It doesn't seem to be. If not what is the new way to run these tests. The documentation still points to this way of testing - so if possible it would be good to put in a method which replicates this old method of doing the testing (or updating the documentation). Many thanks.

**Comment by pchtsp** [comment]
It has not reached pip yet, for now you would have to do as previously shown. That said, we will publish soon a new version to github with this fix.

**Comment by stumitchell** [comment]
@pchtsp can we push master to pip. I am not sure on our new deploy

**Comment by Ptero793** [comment]
i am also having this issue and attempting this command 

`pip install git+https://github.com/coin-or/pulp@add_tests_to_package`

Will confirm if/when this works. 

@pchtsp  thank you in advance and please let us know when documentation has been updated.

**Comment by pchtsp** [comment]
the change is now in pypi. just do the regular `pip install -U pulp`
